export const USERS_DATA = [
  {
    id: 1,
    name: 'Felita Eves',
    position: 'Safety Technician IV',
    email: 'feves0@deviantart.com',
    avatar: 'https://robohash.org/dignissimosutrepudiandae.png?size=407x380&set=set1',
    organizations: [
      { name: 'Atls', organizationLogo: '/organization-logos/atlantis.png' },
      { name: 'Dream-team', organizationLogo: '/organization-logos/atlantis-academy.png' },
      { name: 'LOL', organizationLogo: '/organization-logos/deltadoc.png' },
      { name: 'Freelance', organizationLogo: '/organization-logos/atlantis.png' },
    ],
    time: '12:29:33',
    services: [
      { id: 1, name: 'Git', checked: true },
      { id: 2, name: 'Telegram', checked: false },
      { id: 3, name: 'Discord', checked: false },
      { id: 4, name: 'Figma', checked: true },
      { id: 5, name: '2FA', checked: false },
      { id: 6, name: 'Discord', checked: false },
      { id: 7, name: 'Telegram', checked: false },
      { id: 8, name: 'Discord', checked: false },
      { id: 9, name: 'Telegram', checked: false },
      { id: 10, name: 'Discord', checked: false },
    ],
  },
  {
    id: 2,
    name: 'Kordula Adcocks',
    position: 'VP Sales',
    email: 'kadcocks1@slashdot.org',
    avatar: 'https://robohash.org/estquasimodi.png?size=407x380&set=set1',
    organizations: [
      { name: 'Atls', organizationLogo: '/organization-logos/atlantis.png' },
      { name: 'LOL', organizationLogo: '/organization-logos/deltadoc.png' },
      { name: 'Freelance', organizationLogo: '/organization-logos/atlantis.png' },
    ],
    time: '6:19:44',
    services: [
      { id: 1, name: 'Git', checked: true },
      { id: 2, name: 'Telegram', checked: false },
      { id: 3, name: 'Discord', checked: false },
      { id: 4, name: 'Figma', checked: true },
      { id: 5, name: '2FA', checked: false },
      { id: 6, name: 'Discord', checked: false },
      { id: 7, name: 'Telegram', checked: false },
      { id: 8, name: 'Discord', checked: false },
      { id: 9, name: 'Telegram', checked: false },
      { id: 10, name: 'Discord', checked: false },
    ],
  },
  {
    id: 3,
    name: 'Tootsie Cornish',
    position: 'Financial Advisor',
    email: 'tcornish2@youku.com',
    avatar: 'https://robohash.org/autsuntest.png?size=407x380&set=set1',
    organizations: [
      { name: 'Dream-team', organizationLogo: '/organization-logos/atlantis-academy.png' },
      { name: 'LOL', organizationLogo: '/organization-logos/deltadoc.png' },
      { name: 'Freelance', organizationLogo: '/organization-logos/atlantis.png' },
    ],
    time: '3:03:34',
    services: [
      { id: 1, name: 'Git', checked: true },
      { id: 2, name: 'Telegram', checked: false },
      { id: 3, name: 'Discord', checked: false },
      { id: 4, name: 'Figma', checked: true },
      { id: 5, name: '2FA', checked: false },
      { id: 6, name: 'Discord', checked: false },
      { id: 7, name: 'Telegram', checked: false },
      { id: 8, name: 'Discord', checked: false },
      { id: 9, name: 'Telegram', checked: false },
      { id: 10, name: 'Discord', checked: false },
    ],
  },
  {
    id: 4,
    name: 'Jeff Bachmann',
    position: 'Food Chemist',
    email: 'jbachmann3@devhub.com',
    avatar: 'https://robohash.org/explicaboreprehenderitillo.png?size=407x380&set=set1',
    organizations: [
      { name: 'Atls', organizationLogo: '/organization-logos/atlantis.png' },
      { name: 'Dream-team', organizationLogo: '/organization-logos/atlantis-academy.png' },
      { name: 'LOL', organizationLogo: '/organization-logos/deltadoc.png' },
    ],
    time: '19:02:37',
    services: [
      { id: 1, name: 'Git', checked: true },
      { id: 2, name: 'Telegram', checked: false },
      { id: 3, name: 'Discord', checked: false },
      { id: 4, name: 'Figma', checked: true },
      { id: 5, name: '2FA', checked: false },
      { id: 6, name: 'Discord', checked: false },
      { id: 7, name: 'Telegram', checked: false },
      { id: 8, name: 'Discord', checked: false },
      { id: 9, name: 'Telegram', checked: false },
      { id: 10, name: 'Discord', checked: false },
    ],
  },
  {
    id: 5,
    name: 'Malvina Mustarde',
    position: 'Geologist III',
    email: 'mmustarde4@networkadvertising.org',
    avatar: 'https://robohash.org/ipsamessequasi.png?size=407x380&set=set1',
    organizations: [
      { name: 'Atls', organizationLogo: '/organization-logos/atlantis.png' },
      { name: 'Dream-team', organizationLogo: '/organization-logos/atlantis-academy.png' },
      { name: 'LOL', organizationLogo: '/organization-logos/deltadoc.png' },
      { name: 'Freelance', organizationLogo: '/organization-logos/atlantis.png' },
    ],
    time: '22:03:36',
    services: [
      { id: 1, name: 'Git', checked: true },
      { id: 2, name: 'Telegram', checked: false },
      { id: 3, name: 'Discord', checked: false },
      { id: 4, name: 'Figma', checked: true },
      { id: 5, name: '2FA', checked: false },
      { id: 6, name: 'Discord', checked: false },
      { id: 7, name: 'Telegram', checked: false },
      { id: 8, name: 'Discord', checked: false },
      { id: 9, name: 'Telegram', checked: false },
      { id: 10, name: 'Discord', checked: false },
    ],
  },
]
