compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  glob-promise@*:
    dependencies:
      glob: '7.2.3'

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs
