packageExtensions:
  '@atls-ui-parts/sidebar@*':
    peerDependencies:
      '@atls-ui-parts/switch': '*'
  glob-promise@*:
    dependencies:
      glob: '7.2.3'
  '@atls-ui-parts/input@*':
    dependencies:
      '@types/react': '*'
  '@atls-ui-parts/switch@*':
    dependencies:
      '@types/react': '*'

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs
