compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs
