compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs

packageExtensions:
  '@atls-ui-parts/sidebar@*':
    peerDependencies:
      '@atls-ui-parts/switch': '*'
