packageExtensions:
  '@discordjs/rest@*':
    dependencies:
      'magic-bytes': 'npm:magic-bytes.js@1.10.0'
  '@graphql-codegen/plugin-helpers@*':
    dependencies:
      '@graphql-tools/apollo-engine-loader': '8.0.1'
  glob-promise@*:
    dependencies:
      glob: '7.2.3'
  '@atls-ui-parts/input@*':
    dependencies:
      '@types/react': '*'
  '@atls-ui-parts/switch@*':
    dependencies:
      '@types/react': '*'

compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs
