version: '3.8'

services:
  yarn:
    image: node:18.18
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  identity:
    image: node:18.18
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @identity/renderer-entrypoint dev
    ports:
      - '3000:3000'

  identity-build:
    image: node:18.18
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @identity/renderer-entrypoint build
    ports:
      - '3000:3000'

  identity-start:
    image: node:18.18
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @identity/renderer-entrypoint start
    ports:
      - '3000:3000'
