export const REQUIRED_ENV_VAR_NAMES = [
  'NEXT_PUBLIC_GH_CLIENT_ID',
  'NEXT_PUBLIC_GH_CLIENT_SECRET',
  'NEXT_PUBLIC_TOKEN_COOKIE_NAME',
  'NEXT_PUBLIC_INVITE_GH_ORG_NAME',
  'NEXT_PUBLIC_INVITE_FIGMA_URL',
  'NEXT_PUBLIC_INVITE_DISCORD_URL',
  'NEXT_PUBLIC_INVITE_TELEGRAM',
  'SMTP_AUTH_HOST',
  'SMTP_AUTH_PORT',
  'SMTP_AUTH_USER',
  'SMTP_AUTH_PASS',
]
