export const spaces = {
  auto: 'auto',
  defaultPadding: '12px 24px',
  s0: 0,
  s3: 3,
  s4: 4,
  s10: 10,
  s18: 18,
  s1300: 1300,
  s1400: 1400,
  fixed: 'fixed',
  flex: 'flex',
  column: 'column',
  row: 'row',
  center: 'center',
  pointer: 'pointer',
  none: 'none',
  borderBox: 'border-box',
  count: {
    dot: 3,
  },
  sizes: {
    dot: 3,
    input: 52,
    baseSwitchHandleWidth: 28,
    baseSwitchHandleHeight: 12,
    baseSwitchThumb: 12,
    iconSwitchHandleWidth: 70,
    iconSwitchHandleHeight: 28,
    iconSwitchThumb: 24,
    themeSwitchHandleWidth: 92,
    themeSwitchHandleHeight: 42,
    themeSwitchThumbWidth: 34,
    themeSwitchThumbHeight: 22,
    dropdownButtonWidth: 40,
    dropdownButtonHeight: 28,
    modalChildContainerWidth: 486,
    modalChildContainerHeight: 'min-content',
    modalChildContainerMaxWidth: 'calc(100% - 24px)',
    modalChildContainerMaxHeight: 'calc(100% - 24px)',
  },
}
